# Generated by Django 5.2.5 on 2025-08-27 14:06

import web_tool.models
from django.db import migrations, models
from django.utils.crypto import get_random_string

def _gen_code():
    return get_random_string(12)

class Migration(migrations.Migration):

    dependencies = [
        ('web_tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmepayload',
            old_name='payload',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='mmepayload',
            name='code',
        ),
        migrations.RemoveField(
            model_name='mmepayload',
            name='k',
        ),
        migrations.RemoveField(
            model_name='mmepayload',
            name='query_source',
        ),
        migrations.RemoveField(
            model_name='mmepayload',
            name='species',
        ),
        migrations.CreateModel(
            name='MMEJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=_gen_code, max_length=12, unique=True)),
                ('k', models.IntegerField()),
                ('species', models.CharField(max_length=50)),
                ('query_source', models.CharField(choices=[('file', 'file'), ('text', 'text')], max_length=10)),
                ('query_text', models.TextField(blank=True)),
                ('query_filename', models.CharField(blank=True, max_length=255)),
                ('result', models.JSONField()),
                ('rows_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='web_tool_mm_created_73f95e_idx')],
            },
        ),
    ]
